import { redirect } from "next/navigation";
import { ShieldCheck, ArrowRight, FileCheck2, GitBranch, Printer, Snowflake } from "lucide-react";
import { db, ensureReady } from "@/db";
import { users } from "@/db/schema";
import { getSessionUser } from "@/lib/session";
import { loginAs } from "@/app/actions";
import { roleLabel } from "@/lib/workflow";

export const dynamic = "force-dynamic";

const ORDER = ["initiator_branch", "initiator_npa", "initiator_csd", "reviewer_oi", "reviewer_bm", "brops", "cad"];

export default async function LoginPage() {
  const existing = await getSessionUser();
  await ensureReady();
  if (existing) redirect("/dashboard");

  const all = await db.select().from(users);
  const sorted = all.sort((a, b) => ORDER.indexOf(a.role) - ORDER.indexOf(b.role));

  return (
    <div className="flex min-h-screen">
      {/* Brand panel */}
      <div className="side-grid dark-scroll relative hidden w-[46%] flex-col justify-between overflow-hidden bg-side p-10 lg:flex">
        <div className="flex items-center gap-2.5">
          <div className="flex size-9 items-center justify-center rounded-md bg-pine">
            <ShieldCheck className="size-5 text-white" />
          </div>
          <div>
            <div className="font-display text-[17px] font-semibold leading-none text-white">DigiHost</div>
            <div className="mt-1 font-mono text-[9.5px] uppercase tracking-[0.22em] text-white/45">Blacklist Release</div>
          </div>
        </div>

        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.28em] text-gold">Standard Operating Procedure · Cheque &amp; NPA</div>
          <h1 className="mt-5 font-display text-[44px] font-medium leading-[1.06] tracking-tight text-white">
            The blacklisting release process,
            <span className="text-goldsoft"> end to end in one system.</span>
          </h1>
          <p className="mt-5 max-w-md text-[14px] leading-relaxed text-white/55">
            Case initiation with DigiHost auto-population, maker-checker review, BROPs pool claim,
            auto-generated CIB release letters, CAD/CIC final validation and eligible auto-unfreeze —
            with email-based case movement eliminated.
          </p>

          <div className="mt-10 space-y-3.5">
            {[
              { icon: GitBranch, t: "Six release types, one controlled loop", s: "Applicant & A/C holder cheque, court, NPA, partial guarantor and six-month temporary release." },
              { icon: FileCheck2, t: "Mandatory inputs enforced", s: "Return/Query remarks, CAD/CIC attachments, CIB request numbers and type-specific document checklists." },
              { icon: Printer, t: "Letters generated by the system", s: "Individual and entity formats; digital signature uploaded instead of print-and-scan." },
              { icon: Snowflake, t: "Auto-unfreeze after release only", s: "Single freeze reason code 002, 025 or 100 — never before CAD/CIC release." },
            ].map((f) => (
              <div key={f.t} className="flex items-start gap-3.5 rounded-lg border border-white/10 bg-white/5 p-3.5">
                <div className="flex size-8 shrink-0 items-center justify-center rounded-md bg-pine/80">
                  <f.icon className="size-4 text-white" />
                </div>
                <div>
                  <div className="text-[13px] font-medium text-white">{f.t}</div>
                  <div className="mt-0.5 text-[11.5px] leading-relaxed text-white/45">{f.s}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="font-mono text-[9.5px] uppercase tracking-[0.2em] text-white/30">
          Demo environment · Seeded operational data · PostgreSQL-backed workflow
        </div>
      </div>

      {/* Sign-in panel */}
      <div className="paper-grain flex flex-1 items-center justify-center px-6 py-12">
        <div className="w-full max-w-xl">
          <div className="mb-8 lg:hidden">
            <div className="font-display text-2xl font-semibold text-ink">DigiHost — Blacklist Release</div>
          </div>
          <div className="font-mono text-[10px] uppercase tracking-[0.28em] text-gold">Sign in to the console</div>
          <h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-ink">Choose your operating role</h2>
          <p className="mt-2 text-[13px] leading-relaxed text-ink2">
            The workflow routes each case by role. Pick a demo identity below — you can switch roles at any time from the sidebar.
          </p>

          <div className="mt-8 space-y-2">
            {sorted.map((u, i) => (
              <form key={u.id} action={loginAs.bind(null, u.id)}>
                <button
                  type="submit"
                  className="group flex w-full items-center gap-4 rounded-lg border border-line bg-card px-4 py-3 text-left transition-all hover:border-pine/40 hover:bg-white hover:shadow-md hover:shadow-ink/5"
                >
                  <span className="font-mono text-[10px] text-ink3 w-6">{String(i + 1).padStart(2, "0")}</span>
                  <span className="flex size-9 items-center justify-center rounded-full bg-pinedeep text-[11px] font-semibold text-white">
                    {u.name.split(" ").map((w: string) => w[0]).join("")}
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="block text-[13.5px] font-medium text-ink">{u.name}</span>
                    <span className="block truncate text-[11.5px] text-ink2">
                      {u.title} · {u.unit}
                    </span>
                  </span>
                  <span className="hidden rounded-full border border-line px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider text-ink2 sm:block">
                    {roleLabel(u.role)}
                  </span>
                  <ArrowRight className="size-4 text-ink3 transition-transform group-hover:translate-x-1 group-hover:text-pine" />
                </button>
              </form>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
